### ISSUE TITLE
Create Consultations Workflow

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-her#34]
This should include the following workflow steps:

- [x] Consultation Address
- [x] Consultation Name
- [ ] Area Map (perhaps just add the map widget until the mapping card component is available archesproject/arches#4670)
- [ ] Application Details
- [ ] Reference Numbers (perhaps just stub this out until ticket #27 is completed)
- [ ] Application Proposal
- [ ] Contacts (perhaps just stub this out until (archesproject/arches#4664) is completed)

Be sure to consult the latest mockups and @dwuthrich to confirm step content

Consult the latest mockups and @dwuthrich to confirm the content of each step.

**Comment by chiatt** [comment]
Use the workflow stubbed out in #28 if #28 is already completed

**Comment by chiatt** [comment]
Meets requirements. There is some outstanding work on this workflow that is specified in other tickets in staging
